spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.26.59.35:3306/WK_OMS_WORKORDER
    username: mysqluser
    password: mysqluser
mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.wang.test.enums
  mapper-locations: classpath:/mapper/**.xml
logging:
  level:
    com.wang.test.mapper: debug